repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.3"
    hooks:
      - id: codespell
        args: ["-I", "codespell.txt"]
        exclude: '.*\.yml'
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.9.9"
    hooks:
      - id: prettier
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
exclude: 'node_modules/\.*|.*\.svg|package-lock\.json'
ci:
  autoupdate_schedule: monthly
